use sts_map_oracle::format_map;
use sts_map_oracle::generate_maps;

const MAP_HEIGHT: i32 = 15;
const MAP_WIDTH: i32 = 7;
const PATH_DENSITY: i32 = 6;

#[test]
fn check_output_for_readme_example() {
    let seed = 673465884448;
    let maps = generate_maps(seed, MAP_HEIGHT, MAP_WIDTH, PATH_DENSITY);
    assert_eq!(format_map(&maps[0]), "\n                           \n14     R  R        R     R \n         \\|      / |   /   \n13        ?     M  M  M    \n            \\     \\  \\  \\  \n12           R     M  E  ? \n           /   \\   |  |/   \n11        ?     ?  E  ?    \n          |     |  |  | \\  \n10        M     M  R  $  R \n          |   /      \\|  | \n9         M  R        M  E \n          |  |        |/ | \n8         T  T        T  T \n          |  |      / |  | \n7         M  E     M  ?  M \n          |  |       \\| \\| \n6         E  M        M  ? \n        /    |      /   \\| \n5      R     E     M     E \n         \\     \\ /     / | \n4         M     ?     M  ? \n          |     | \\ /  / | \n3         M     M  M  M  ? \n        /     /  /  /  /   \n2      $     M  ?  $  ?    \n         \\     \\|/  /      \n1         M     M  ?       \n        /     /      \\     \n0      M     M        M    ");
    assert_eq!(format_map(&maps[1]), "\n                           \n14     R  R  R  R          \n       |/   \\|/            \n13     E     $             \n       | \\ / | \\           \n12     ?  M  ?  M          \n       |  | \\|    \\        \n11     ?  M  ?     E       \n       |/    | \\ /         \n10     M     ?  M          \n       | \\ /      \\        \n9      E  M        R       \n       |  |      / |       \n8      T  T     T  T       \n       | \\| \\ /      \\     \n7      R  E  R        R    \n       |/ |/            \\  \n6      $  M              E \n       | \\| \\            | \n5      E  R  E           R \n       |/    | \\       /   \n4      M     M  $     M    \n       | \\     \\  \\ /      \n3      ?  M     ?  ?       \n       | \\|   /    | \\     \n2      ?  M  ?     M  M    \n         \\| \\|   /      \\  \n1         M  M  ?        M \n        /  /      \\    /   \n0      M  M        M  M    ");
    assert_eq!(format_map(&maps[2]), "\n                           \n14     R  R        R  R    \n       |  |      /    | \\  \n13     ?  E     ?     M  M \n       |/     /       |/   \n12     $     R        E    \n       | \\ /          | \\  \n11     E  M           M  M \n       |  | \\       /  /   \n10     M  E  M     ?  ?    \n         \\|  |     |  |    \n9         ?  M     ?  ?    \n        / |  |     |    \\  \n8      T  T  T     T     T \n       | \\  \\  \\ /     /   \n7      R  R  $  M     ?    \n       |  |/    |   /      \n6      E  M     R  E       \n       |/   \\ /   \\  \\     \n5      R     E     E  R    \n       | \\     \\     \\  \\  \n4      ?  M     M     ?  M \n       |  |     | \\ /  /   \n3      M  ?     ?  M  M    \n         \\|       \\| \\  \\  \n2         M        M  M  $ \n          |      / |    \\| \n1         M     M  ?     M \n        /     /      \\ /   \n0      M     M        M    ");
}

#[test]
fn check_output_for_other_example() {
    let seed = 2780424839485660359;
    let maps = generate_maps(seed, MAP_HEIGHT, MAP_WIDTH, PATH_DENSITY);
    assert_eq!(format_map(&maps[0]), "\n                           \n14     R     R     R  R  R \n         \\   |       \\|/   \n13        M  M        M    \n          |  |        | \\  \n12        M  M        M  M \n        /      \\    /  / | \n11     ?        ?  M  M  R \n         \\      |/      \\| \n10        ?     M        ? \n            \\ /        / | \n9            E        E  R \n             | \\    /  / | \n8            T  T  T  T  T \n           / |    \\|/  /   \n7         E  M     E  M    \n            \\|     |/      \n6            M     ?       \n           /   \\ / | \\     \n5         R     E  E  R    \n          |     |    \\| \\  \n4         M     ?     M  ? \n            \\ /   \\   |/   \n3            M     M  ?    \n           /         \\| \\  \n2         $           ?  $ \n        /           / |/   \n1      M           ?  ?    \n       |         /  /      \n0      M        M  M       ");
    assert_eq!(format_map(&maps[1]), "\n                           \n14     R  R     R     R    \n         \\  \\   | \\   |    \n13        ?  E  ?  M  M    \n          |/      \\|/      \n12        M        $       \n        / |        | \\     \n11     R  ?        M  R    \n       |  |      / | \\  \\  \n10     M  M     E  M  M  ? \n       |  |     |/      \\| \n9      M  E     M        M \n         \\|       \\    /   \n8         T        T  T    \n        /   \\    / |/ |    \n7      R     ?  M  ?  E    \n       |     |  |/ |  |    \n6      E     R  ?  E  M    \n       |     |/      \\|    \n5      R     E        R    \n         \\ / |        | \\  \n4         ?  $        M  M \n        / |/        /    | \n3      ?  M        ?     ? \n         \\| \\      |     | \n2         ?  M     ?     M \n        / |/     /     /   \n1      M  M     M     M    \n       |  |     |       \\  \n0      M  M     M        M ");
    assert_eq!(format_map(&maps[2]), "\n                           \n14     R     R     R     R \n       | \\ / |   /       | \n13     E  E  ?  M        E \n       |  | \\|/          | \n12     M  ?  $           M \n         \\|/ | \\         | \n11        R  E  R        M \n        / |  |  |      /   \n10     M  M  ?  ?     ?    \n       | \\  \\  \\  \\   |    \n9      ?  M  ?  M  M  R    \n         \\  \\|  |    \\|    \n8         T  T  T     T    \n            \\|/       |    \n7            M        M    \n           / | \\      |    \n6         E  M  M     ?    \n        /  / |  |   / |    \n5      R  R  E  R  M  R    \n       |  |/      \\|    \\  \n4      M  ?        M     ? \n         \\|        | \\ /   \n3         M        ?  M    \n        /          |  | \\  \n2      M           M  ?  $ \n       | \\           \\|/   \n1      ?  $           M    \n       |  |         /      \n0      M  M        M       ");
}
